### ISSUE TITLE
Umbrella: Resizing issues

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1298]
There are several resizing issues and PRs. We probably need to organize them.

- [x] #1218 Resize multiple elements
- [x] #1275 Resizing curved lines from W/N doesn't fix E/S (PR #1427)
- [x] #1024 Resize elements from center point (PR #1225)
- [x] #1296 Resizing with SHIFT loses the pointer position (PR #1330)
- [ ] #690 Pressing "shift" when resizing a rectangle sets the aspect ratio to square (PR #768)
- [x] #1122 support negative resize for multi-point arrows (PR #1237) (obsoletes PR #1214)
- [x] #1334 Negative resize swaps arrow direction
- [x] #1339 applyResizeArrowFn to be position based (no lastX)
- [ ] #1340 Apply resize on SHIFT key down/up
- [x] #1443 negative resize flicker bug (PR #1475)
- [ ] #1342 Enhance aspect ratio tools (PR #1467)
- [x] #1505  Resizing elements should offset initial cursor delta
- [x] #1506 Negative resizing should be continuous
- [x] #1603 Support resizing text (PR #1650)
- [ ] #1950 resize elements at the edge-handle with "shift" broken
- [ ] #1989 Allow horizontally/vertically resizing multiple elements

## Dependency graph

https://excalidraw.com/#json=6279784233435136,0-oFj0-LTyYpjPhQypXNHg

![image](https://user-images.githubusercontent.com/490574/84020743-471a2e80-a9be-11ea-91f0-f62e6e02d21e.png)

**Comment by dai-shi** [comment]
#1296 should probably be resolved before #1122 and #690, because they will have the same problem.
Cc: @enzoferey @lusingander

**Comment by dai-shi** [comment]
#1275 could be important to be fixed before #1218.

**Comment by lipis** [comment]
I updated the list to somehow reflect that :) Change if you have better ideas

**Comment by dai-shi** [comment]
#1024 is probably less related with others. #1255 needs to follow the new `resizeElements.ts`introduced in #1193 
Cc: @jquintozamora 

But, it may conflict anyway, if #1296 is a big change and it can be.

**Comment by dai-shi** [comment]
@lipis You broke the list somehow...
And, I meant #1296 *should* be come before others.

**Comment by jquintozamora** [comment]
> #1024 is probably less related with others. #1255 needs to follow the new `resizeElements.ts` introduced in #1193
> Cc: @jquintozamora

Perfect @dai-shi , I will use the new `resizeElements` and also meanwhile I find the perfect equation for resize from center I give more time to #1296 to be completed and resolve any conflicts as well.

**Comment by lipis** [comment]
@dai-shi Something went wrong.. feel free to revert.. there is a history edit :)

**Comment by dai-shi** [comment]
@lipis Looks like it's fixed. Thanks. I will find a better way.

**Comment by dai-shi** [comment]
@jquintozamora Would you be tackling #1296 before #1024? Check out my comment in #1296, I'm not 100% confident, but you will get it.

**Comment by jquintozamora** [comment]
Yes, I can see that #1296 is related to the changes I'm implementing for #1024 , the fact that we should return to the previous position.

**Comment by dai-shi** [comment]
@lipis 

> Change if you have better ideas

Yay, we *are* Excalidraw developers!

**Comment by lipis** [comment]
#1339 and #1340 should be part of the list too..

**Comment by dai-shi** [comment]
Added. I'll update the diagram too.

**Comment by dai-shi** [comment]
https://excalidraw.com/#json=4703779244998656,0zlCJnTKVrhgST8dzMXN7g

![Untitled-2020-04-10-0026](https://user-images.githubusercontent.com/490574/78912918-2ec38b80-7ac3-11ea-850a-c6c72263dfa2.png)

**Comment by dai-shi** [comment]
@dwelle Hi, #1225 is somewhat blocking and priority.

**Comment by dai-shi** [comment]
We are almost there.

I will be working on #1218 sometime soon.

As for #1340, would someone take this? Cc @jquintozamora @dwelle 

How about #690 and #1342? @enzoferey @quuu ?

**Comment by enzoferey** [comment]
I do remember starting to solve #1340 at #768, but your comment at https://github.com/excalidraw/excalidraw/pull/768#issuecomment-620346512 makes me doubt about it now 🤔 

After all this time the code is pretty worthless I think, so I would personally start from scratch if I had to start again. I still don't have any time to spend on Excalidraw though, so please whoevers wants feel free to pick it up.

**Comment by dai-shi** [comment]
Yeah, I think you/we/someone would need to start from scratch. It's been changed quite a bit.

I wouldn't label them as "good first issue," but we welcome any contributors!

**Comment by lipis** [comment]
Closing the umbrella issues as all the remaining issues are already filed.
