### ISSUE TITLE
Refactor, Consistency

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1320]
### Consistency

- [x] Use Prettier and ESLint
- [x] Use commit hooks
- [ ] One style for all function declarations: `=>` (ongoing #1210)
- [ ] Some variable names (#1272)
- [ ] Sort all JSON files (controversial)
	- Pros
		- Easier to scan manually to find a property
        - No dangling comma issue when inserting at the end a new property
        - Nothing to think about when adding new strings to `en.json`
        - No conflicts with existing PRs and will be done in one go
        - Changing `en.json` Crowdin will automatically sort the rest for us
    - Cons
        - Annoying PR
        - No automation for it
        - Maybe manually sort all if out of control (not an issue since we only have a bunch)

### Refactor

- [ ] `App.js` is out of control :) #1309 
- [ ] End 2 End tests #691 
- [ ] Something else that got too big and needs splitting?
