### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by klikstermkd** [excalidraw/excalidraw#138]
It would be great if the tool supports mobile touch, so it can be used on devices such as tablets with a pencil.

---

Progress:

- [x] Responsive UI (#787)
- [x] touch support (#788)
- [x] make the touch areas for the resize handles larger (they shouldn’t appear visually larger though) (#790)
- [x] two-finger pan/zoom (#788)
- [x] fix press&hold on canvas triggering selection (maybe it’s not fixed? hard to tell) → fix by disabling user-select everywhere (#790)
- [x] edit text (#790)
- [x] delete objects (toolbar button?) (#788)
- [x] finalize line creation (#788)
  - [x] fix how existing `finalize` action deletes last line (#790)
- [x] refactor menu/edit toggles to be actions (#793)
- [x] make 🍔/🎨 buttons radios or otherwise show that they’re selected (#793)
- [ ] “reset zoom” button/indicator
- [x] undo/redo buttons (#793)
- [x] desktop pinch-zoom (Safari GestureEvents, Chrome/FF simulated ctrl+wheel)
- `apple-touch-icon` for adding to home screen ⏩ #820
- [ ] test `pointercancel`
- [ ] test two-finger gestures programmatically
- [ ] abort tap selection if a second `pointerdown` (i.e. for pan/zoom) occurs before the first pointer moves too far
- [ ] desktop pinch-zoom centered around cursor
- [ ] fix scrollbar offsets to account for toolbar (or resize canvas)
- re-add lock button somewhere ⏩ #819

Optional:
- [ ] multiple selection
- [ ] two-finger gestures while creating a line
- [ ] support releasing one finger from a two-finger gesture to switch back to select/edit mode (the reverse currently works)

**Comment by hmaurer** [comment]
Basic support might be as simple as switching from mouse events to pointer events (`onMouseDown` -> `onPointerDown`, etc).

**Comment by vjeux** [comment]
I think that there are a few things here:
- Make sure we react to touch events
- Update the layout on mobile so that 3/4 of the view are not just the left page
- Optimize touch interactions. We can double finger drag to resize an element. Figure out how selection and pan interact...
- Add visible buttons for copy paste, undo...

We don’t need to do everything at once, every small improvement would be welcome

**Comment by davidbonan** [comment]
I think, a mobile support is not a good idea but, a tablet support will be very cool

**Comment by klikstermkd** [comment]
@davidbonan Mobile support covers tablets as well, as I have said in the description of the issue.

**Comment by dwelle** [comment]
Yes, IMO we should aim for touch/pointer support, but not sweat about making the design responsive in a way that it fits on tiny screens.

**Comment by cryptobias** [comment]
> Basic support might be as simple as switching from mouse events to pointer events (`onMouseDown` -> `onPointerDown`, etc).

It seems to be. I quickly tested it over [here](https://github.com/cryptobias/excalidraw/pull/1) and it worked quite well on my laptop's touchscreen.

I haven't tested it on mobile yet and haven't made sure that mouse isn't broken though.

**Comment by dwelle** [comment]
Here's a [codesandbox](https://codesandbox.io/s/github/cryptobias/excalidraw/tree/touch-input-support) (and [direct link](https://qsdzx.csb.app/)) if anyone wants to quickly test @cryptobias's solution.

Haven't tested on mobile/touchscreen, but if Chrome devTools' mobile emulation does at least some justice (which it likely doesn't), then it indeed does not work for touch devices.

We'd likely need to implement `touchmove` etc., separately. Not sure why `pointermove` doesn't work, though.

**Comment by voluntadpear** [comment]
Just tested the Codesandbox on my Android phone. I'm able to start drawing and resizing a rectangle but the pull-to-refresh gesture from my phone gets in the way.

I think the switch to pointer events should work but we might need to prevent these native gestures from getting in the way, and try additional things like setting the [`touch-action` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), attaching the events to the canvas element directly instead of relying on React's synthetic events (which are bound to the `document`), etc

**Comment by voluntadpear** [comment]
Adding

```js
```

works on my Android  🎉

Can someone with other devices try this [Codesandbox](https://codesandbox.io/s/excalidraw-touch-action-none-ukovm)?

**Comment by dvir** [comment]
Excited for this!

That last sandbox works pretty well for me on Chrome for Android, and another custom Chromium browser. Happy to get double-tapping fixed on top of this, did a quick hack for it in https://codesandbox.io/s/excalidraw-touch-action-none-53shx

An important missing gesture is scrolling around (otherwise the canvas size is small), but perhaps can be added incrementally. That, and refactoring the code around these as it became quiet large :P

**Comment by j-f1** [comment]
TODOs once #787 is merged:

- [ ] touch support
- [ ] make the touch areas for the resize handles larger (they don’t have to appear visually larger though)
- [ ] two-finger pan/zoom
- [ ] fix press&hold on canvas triggering selection

**Comment by j-f1** [comment]
How should scrollbars work? Should I hide them or should they be draggable?

**Comment by vjeux** [comment]
I would definitely display them. I don’t think that making them actually draggable is needed

**Comment by j-f1** [comment]
Are we good to close this or should we polish off the last checkboxes?

**Comment by vjeux** [comment]
Closing this as mobile support is in a pretty good shape now! If there are any more follow ups we should create standalone issues.

**Comment by j-f1** [comment]
Done!
