### ISSUE TITLE
Umbrella: Grid mode issues

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1810]
- [x] :bug: don't export grid to PNG #1811
- [x] edit multi-point lines #1984 
- [ ] create new elements (multi-point lines) #2009 
- [ ] create new elements (texts)

----

- [ ] [maybe] customize grid size

**Comment by lipis** [comment]
Regarding grid size customisation: https://github.com/excalidraw/excalidraw/pull/1788#issuecomment-647637795

**Comment by lipis** [comment]
Closing this umbrella in favor of https://github.com/excalidraw/excalidraw/issues/2009 #2663
