### ISSUE TITLE
Umbrella: Library improvements

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1904]
I think the library could be improved a lot. I probably won't have time to get around to it so this would be a great set of tasks for someone new to the project to take on. These include:

- [x] Play with the rendering of the library grid. The squares could be smaller or adjust their size
- [x] Make it more usable on mobile
- [x] Create a way to import and export your library to a file #1901
- [x] Add a repo where people can share their libraries: https://libraries.excalidraw.com
- [x] ~~Add standard library #1923~~
- [x] Clean up the UX around adding to the library. I don't actually know exactly what to do here, but anything is better than what I did :)

**Comment by sw-yx** [comment]
didnt know this feature was implemented!

was there a discussion about importing svg iconsets or logos? or is it implemented and i missed it somewhere? i think that was an important part of the previous discussion (#1091)

**Comment by dwelle** [comment]
> was there a discussion about importing svg iconsets or logos? or is it implemented and i missed it somewhere? i think that was an important part of the previous discussion 

I missed that. The only reference to "icons" is in this comment: https://github.com/excalidraw/excalidraw/issues/1091#issuecomment-624096930, and I understood it to be just a predefined library shapes, which is now tracked here: https://github.com/excalidraw/excalidraw/issues/1923

Importing SVGs was discussed somewhere but current consensus is that's a no go as we'd either need to write a parser for SVG → excalidraw (roughjs) shapes (pretty much intractable), or render the [SVG onto canvas verbatim](https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D), but then we'd need to reimplement most of manipulation logic because the SVG wouldn't be an actual excalidraw element we can work with. Maybe there's a third way I haven't considered.

**Comment by sw-yx** [comment]
thanks @dwelle i admit it could be me projecting my own desires on that issue haha.

understood on the difficulties with SVG. perhaps we can have a separate "layer", where we can separate the manipulation logic specifically for imported assets, and then collapse them for canvas export if needed. just brainstorming

**Comment by dwelle** [comment]
Actually, one other possibility is to create a new element type which will act as a regular element (have `width`,`height`,`x`,`y` etc.), but will contain `svg` prop which will be used for render.

In fact, something along these lines would also be used for #19.

**Comment by msal4** [comment]
- [x] Play with the rendering of the library grid. The squares could be smaller or adjust their size.
   -  I made it half the size and fit 6 cells in a row.
- [ ] Make it more usable on mobile.
   - Currently doing this one.

**Comment by marcofranssen** [comment]
Are there any references to some nice excalidrawlib galleries with drawings created by others?

**Comment by lipis** [comment]
Most of these features are done and generally the library looks nice on desktop and mobile.. file separate issues if needed.

### P.S. We have an official public directory for user libraries https://libraries.excalidraw.com
