### ISSUE TITLE
Umbrella: arrow/line binding

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2019]
# features

- [ ] support binding non-arrow lines
- [ ] support unbinding parent shapes same as we support unbinding arrows (via CMD/CTRL modifier)

**Comment by lipis** [comment]
Binding text to lines/arrows sounds like a good idea.. but there might be lots of edge cases.. what should happen if the red circle (from your gif) will be moved beyond the right circle (all the way to the right)

**Comment by dwelle** [comment]
Yea there are many problems with it to the point where it may not be easily implementable. Just throwing it out there.

**Comment by xixixao** [comment]
Don't think you need to rotate the text, it can overlap the line. Here are the original follow ups from my PR #1899:


- [ ] Allow binding to closed loops
- [ ] Use [inverse kinematics](https://enkimute.github.io/ganja.js/examples/coffeeshop.html#pga2d_inverse_kinematics) to adjust inner points of a bound multi-point linear element
- [ ] Don't allow binding across a shape (https://github.com/excalidraw/excalidraw/pull/1899#issuecomment-668353189) (also https://github.com/excalidraw/excalidraw/pull/1899#issuecomment-668592705)
- [ ] Binding should prefer closer elements instead of using z-index order (https://github.com/excalidraw/excalidraw/pull/1899#issuecomment-668592705)

**Comment by xixixao** [comment]
[ ] The highlight of binding area has sharp corners, but the implementation uses distance to shape (so is rounded with circle arches). Align the two (either rounding the rendering or sharpening the implementation). Low pri.

**Comment by adrydale** [comment]
Any movement on this one? Would be great to be able to bind/connect normal lines to objects like arrows.

**Comment by dwelle** [comment]
@adrydale we decided against supporting binding on non-arrow lines because we want to keep lines as primitive as possible since they are used for creating complex shapes and generally their behavior is different from arrows.

You can remove the arrowhead from your arrow to make it look like a line, and it'll still be bindable:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/3247e3c9-c8c2-4a42-8e4a-7ad7dd469fc8)

**Comment by ADTC** [comment]
> we decided against supporting binding on non-arrow lines

@dwelle could you make an opt-in hack where using the line tool will draw an "arrow without arrowheads" instead of a regular line? Then it can snap to objects. It's basically what you suggested above, but automated. Opt-in for those who will find it useful. :)

**Comment by feridsassi** [comment]
For anyone looking for this — you can achieve bindable undirected lines by using the arrow tool and removing both arrowheads. The arrow will still bind to shapes when you move them, and visually it looks identical to a regular line.
