### ISSUE TITLE
API update once export redesign is merged

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3638]
API wise I am thinking of the below changes :point_down: once #3613 is merged

**changes in `UIOptions.canvasActions`**

- [x] `export` prop will now be used in the new export dialog #3662,
- [x]  Rename`saveAsScene` to `saveFileToDisk` will be used to render save button inside export dialog but it will be no more part of canvas actions #3658, 
- [x]  Rename `saveScene` to `saveToActiveFile` will be used for active file saving #3657 .
- [x]   `saveAsImage` will be added to show image export dialog #3662
- [x]  we can update the type of `export` to be `boolean`/`object` something like 👇🏻 #3658 

```js
export: {
    saveFileToDisk: true,
    exportToBackend: Function,
}
```
- [x] Add `renderCustomExportUI: Function` in export prop to support custom UI rendering https://github.com/excalidraw/excalidraw/pull/3666

cc @dwelle

**Comment by ad1992** [comment]
Yep updated the description

**Comment by dwelle** [comment]
Maybe to disambiguate the `saveAs`/`saveAsScene`, we can use `saveToDisk`/`saveToActiveFile`?

**Comment by ad1992** [comment]
Yeah even I thought the same earlier but wanted to avoid props renaming, but better naming will surely help so let's to that 👍🏻

**Comment by ad1992** [comment]
closing as the task list is done
