### ISSUE TITLE
disallow grouping bound containers to themselves

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6579]
```[tasklist]
### Tasks
- [ ] disallow grouping text containers or labeled arrows with themselves
- [ ] if you copy such container from inside a group and paste outside that group, make sure the group ids are stripped
- [ ] repair such existing groups on restore (legacy)
- [ ] if we end up with such invalid grouping anyway, make sure that selecting such a container ignores the group
```

steps:

1. create text container or labeled arrow
2. `cmd/ctrl-G` to group
3. shouldn't be allowed

**Comment by codingmickey** [comment]
Does this need help I can try this one (would take some time maybe, I'll have to go through a lot of code for this one)

Also, one question that I had is why aren't you guys shifting to functional components from class-based components.
