### ISSUE TITLE
Support more handwritten fonts in different languages

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#6679]
There has been lot of requests to support handwritten font in different languages eg Chinese, Japanese, Arabic and more so creating this issue for linking all of theme at one place.

```[tasklist]
### Tasks
- [ ] Arabic Handwritten font support #6619 
- [ ] Chinese Handwritten font support #6394, #5665, #5259
- [ ] Japanese Handwritten font support #1615
- [ ] Hebrew Handwritten font support #5633
```

`Chinese` is requested the most so we can start with supporting Chinese

**Comment by DanielJGeiger** [comment]
@ad1992 I think #6966 could work well here, easily covering the above languages and more.

**Comment by hezhongfeng** [comment]
Looking forward to the support of handwritten Chinese fonts

**Comment by hezhongfeng** [comment]
@DanielJGeiger thanks, I will do it.

**Comment by hulkbig** [comment]
@ad1992  hey, you can try my fork version. [https://excalidraw-zh.com/](url)

**Comment by lwdsw** [comment]
nice job

**Comment by mangteboy** [comment]
I hope for the support of Korean handwritten fonts.

**Comment by Mrazator** [comment]
@mangteboy Actually we will be releasing support for the whole CJK (https://github.com/excalidraw/excalidraw/pull/8530) soonish!

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/

**Comment by dustookk** [comment]
Hi there! I was wondering if there are any updates on this feature request from last year?

**Comment by Mrazator** [comment]
@dustookk as mentioned in the previous comments, support for handwritten CJK was added recently, are you asking about something specific?

**Comment by dustookk** [comment]
@Mrazator Sorry, I didn't notice the previous reply, thank you for the reminder

**Comment by sambensim** [comment]
It would also be nice for more unicode character support as handwritten characters!

**Comment by Mrazator** [comment]
@sambensim what kind of characters are you missing? For Excalifont we are gathering some missing characters in https://github.com/excalidraw/excalidraw/issues/8838, at one point we will hopefully release new Excalifont version with the most requested missing characters.
