### ISSUE TITLE
docs @0.18.0

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#7786]
```[tasklist]
### Tasks
- [ ] collab cursor color/disable https://github.com/excalidraw/excalidraw/pull/7130
- [ ] custom Stats sub-components https://github.com/excalidraw/excalidraw/pull/8361
- [ ] `<DefaultSidebar.Triggers/>` changes https://github.com/excalidraw/excalidraw/pull/8498
```

**Comment by Mrazator** [comment]
For future reference, there is already a PR:
https://github.com/excalidraw/excalidraw/pull/7911

**Comment by Mrazator** [comment]
Moved the tasklist to the release PR #9127.
