### ISSUE TITLE
Stabilise `Store` component

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#7914]
`Store` component was introduced as part of the multiplayer undo / redo #7348, in order to abstract away capturing of local `Change`s to the elements and the (observed) appState. At the time, it was designed to be plugged in front of the existing `History` component, without affecting (too much) the rest of the codebase. Hence we accepted some tradeoffs, which we should now reconsider, refactor away and improve as part of the stabilisation initiative.

### Unify `Store` data flow for local updates

Local changes within the editor are still being recorded after the `App` component updates. This means that our data flow of capturing changes is `action` -> `componentDidUpdate` -> `store`, but updates through the `updateScene` API end up in the `Store` before component updates - to filter out yet uncommitted local elements and eliminate potential concurrency issues.

As stated in https://github.com/excalidraw/excalidraw/pull/7348#discussion_r1516057935, we should not capture the _increments_ post component update, but emit them from the user actions and apply them to the `Store` directly. Additionally, turning on recording in relevant actions and capturing the changes after component updates does not just seem error-prone, but might also lead to unexpected issues related to `React`'s auto-batching & concurrent mode.

Moreover, from the event sourcing perspective, coupling renders with exactly one user action is just plain wrong - we should be able to have multiple actions as part of one render, as well as one "async" action spread across multiple renders.

> In theory, to support async actions properly, we would likely need to establish transactions on the elements level (with transaction id, rollback possibility, etc.)  in case there are other actions triggered in the meantime - such instances are out of scope of this initiative.

```[tasklist]
### Tasks
- [ ] Update local store data flow from `action` -> `state` -> `componentDidUpdate` -> `store` into `action` -> `store` -> `state`.
```

### Improve handling of ephemerals (WIP)

As their name suggests, _ephemeral_ actions, such as dragging, resizing or drawing, do not fit into the whole `Store` story very well. Ideally, such actions should be streamed over to the other clients as quickly as possible, with as small footprint as possible. 

However, the biggest weak point currently is that each received remote action updates the `Store` snapshot by deep cloning changed elements. For shared scenes with multiple users simultaneously performing multiple ephemeral actions, it's far from the ideal. 

```[tasklist]
### Tasks
- [ ] Consider adding metadata on the element level **TBD**
- [ ] Consider emitting increments for ephemerals directly, without diffing with the previous snapshot, so that we could stream them to other clients
```

- stream 

TBD improving ephemerals
TBD decouple store from the editor
TBD expose `onIncrement`, `applyIncrement`, etc.
TBD decouple store from history
TBD store & increments metadata
TBD exchanging increments
TBD increments migration strategy
TBD store persistence
