### ISSUE TITLE
Unify `Store` data flow for local updates

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#7921]
Local changes within the editor are still being recorded after the `App` component updates. This means that our data flow of capturing changes is `action` -> `componentDidUpdate` -> `store`, but updates through the `updateScene` API end up in the `Store` before component updates - to filter out yet uncommitted local elements and eliminate potential concurrency issues.

As stated in https://github.com/excalidraw/excalidraw/pull/7348#discussion_r1516057935, we should not capture the _increments_ post component update, but emit them from the user actions and apply them to the `Store` directly. Additionally, turning on recording in relevant actions and capturing the changes after component updates does not just seem error-prone, but might also lead to unexpected issues related to `React`'s auto-batching & concurrent mode.

Moreover, from the event sourcing perspective, coupling renders with exactly one user action is just plain wrong - we should be able to have multiple actions as part of one render, as well as one "async" action spread across multiple renders.

> In theory, to support async actions properly, we would likely need to establish transactions on the elements level (with transaction id, rollback possibility, etc.)  in case there are other actions triggered in the meantime - such instances are out of the scope of this initiative.

```[tasklist]
### Tasks
- [ ] Remove scheduling of increments capture and snapshot update post component update
- [ ] Identify and refactor actions which are dependent on multiple `setState` calls or are generally asynchronous
- [ ] Update local store data flow from `action` -> `state` -> `componentDidUpdate` -> `store` into `action` -> `store` -> `state`.
```

> Store should not be considered as a mediator of the state, as it is handling only a subset of state operations. Especially it's interested only in (observed) committed data (no ephemerals).

**Comment by Mrazator** [comment]
Closing for now, #9450 comes with sufficient improvements to update store only post component updates, allowing to schedule multiple (micro) actions and flush them all before the local (macro) action executes - similar to how event loop processes with micro / macro tasks.

Event sourcing the actions directly could be the next step, but as of now it would require huge rewrite; likely it would be better to just start from scratch. We would also lose the simplicity & flexibility of diffing against the snapshot, which hides a lot of ES-related complexity, which we can't afford right now.
