### ISSUE TITLE
Improve handling and exchanging of ephemerals

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#7922]
As their name suggests, _ephemeral_ actions, such as dragging, resizing or drawing, do not fit into the whole `Store` story very well. Ideally, such actions should be streamed over to the other clients as quickly as possible, with as small a footprint as possible. 

However, the biggest weak point currently is that each received remote action updates the `Store` snapshot by deep cloning changed elements. For shared scenes with multiple users simultaneously performing multiple ephemeral actions, it's far from ideal.

The ultimate solution is to avoid deep cloning of elements into the snapshot and not performing "snapshots diffing" at all, which is a far future, as currently we perform the diffing on all local actions. The next best solution, apart from optimising cloning itself, is to keep diffing, but postpone the clone as much as possible. Ideally the clone should be scheduled just once (A) and performed only if it's needed (B). Meaning we could do the following.

```[tasklist]
### Tasks
- [ ] Separate ephemeral updates from committed updates and debounce these updates of snapshot and related necessary cloning per `clientId`. Flush pending updates before locally capturing a change ~ solves (A).
- [ ] Add a logical `source: "local" | "remote"` on the element level (locally computed out of `clientId` or similar), so that we calculate changes only on the "local" updates and clone only remotely modified elements ~ solves (B), also allows to deprecate `filterUncomittedElements`.
- [ ] Consider streaming increments as ephemerals to the other clients and do not perform diffing to obtain them (otherwise it would not be great for perf.). Either way, we will likely want to keep receiving all elements once in a while, to ensure consistency if things go wrong, or at least until increments are SSOT.
- [ ] Consider a different Delta format for ephemerals, containing element ids and expressing operations instead of the state - i.e. imagine dragging thousands of elements, where x and y represent the same Δ on all elements, `Op { x: +10, y: -20 }`.
- [ ] Consider integrating mouse movements into ephemeral `appState`.
```
