### ISSUE TITLE
Decouple `Store` from the editor

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#7923]
```[tasklist]
### Tasks
- [x] Separate `Store` into a standalone package, which could be also potentially used server-side.
- [x] Draw a fine line between the shared functions, utilities & types - likely will need to be separated as well.
- [ ] Test the `Store` independently, as currently it is being tested indirectly by the `History` integration tests (unit, integration & performance tests)
- [ ] Think about an API for a pluggable Store (far future).
```

**Comment by Mrazator** [comment]
Closed by #9450
