### ISSUE TITLE
`History` improvements

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#7932]
Similarly to #7914, this initiative encapsulates follow-ups for `History` related functionalities after a large rewrite in #7348.

```[tasklist]
### Tasks
- [ ] https://github.com/excalidraw/excalidraw/issues/7944
- [ ] https://github.com/excalidraw/excalidraw/issues/7936
- [ ] https://github.com/excalidraw/excalidraw/issues/7937
- [ ] https://github.com/excalidraw/excalidraw/issues/1473
- [ ] https://github.com/excalidraw/excalidraw/issues/7948
- [ ] https://github.com/excalidraw/excalidraw/issues/7933
- [ ] https://github.com/excalidraw/excalidraw/issues/7938
- [ ] https://github.com/excalidraw/excalidraw/issues/7934
- [ ] https://github.com/excalidraw/excalidraw/issues/7924
- [ ] https://github.com/excalidraw/excalidraw/issues/7940
- [ ] https://github.com/excalidraw/excalidraw/issues/5714
- [ ] https://github.com/excalidraw/excalidraw/issues/5437
```
