### ISSUE TITLE
Introduce performance related tests

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#7943]
Introduce performance measures, so that we can keep pushing forward and ensure no regression in the future, especially in the hot paths. 

```[tasklist]
### Tasks
- [ ] Establish benchmarking infrastructure for unit/integration tests
- [ ] Analyse other options on how to measure and detect complexity for certain hot paths
- [ ] Gradually unify performance across various user actions to keep as stable FPS as possible
```
