### ISSUE TITLE
index.html.ninja-mann07.github.io/settings/notifications/excalidraw.obsidian/updates

### ISSUE THREAD

**Issue by Ninja-mann07** [excalidraw/excalidraw#8112]
viewUpdateScene (
    scene: {
      elements?: ExcalidrawElement[],
      appState?: AppState,
      files?: BinaryFileData,
      commitToHistory?: boolean,
      storeAction?: "capture" | "none" | "update",
    },
    restore: boolean = false,
  ):void ;
```[tasklist]
### Tasks
- [ ] https://github.com/excalidraw/excalidraw/pull/8111
- [ ] https://github.com/excalidraw/excalidraw/pull/8108
- [ ] https://github.com/excalidraw/excalidraw/issues/8109
- [ ] https://github.com/excalidraw/excalidraw/issues/8107
- [ ] https://github.com/excalidraw/excalidraw/issues/6777
- [ ] https://github.com/excalidraw/excalidraw/issues/7873
- [ ] https://github.com/excalidraw/excalidraw/issues/8104
- [ ] https://github.com/excalidraw/excalidraw/issues/8106
- [ ] https://github.com/excalidraw/excalidraw/issues/8103
- [ ] https://github.com/excalidraw/excalidraw/issues/8105
- [ ] https://github.com/excalidraw/excalidraw/issues/7903
- [ ] https://github.com/excalidraw/excalidraw/pull/7429
- [ ] https://github.com/excalidraw/excalidraw/pull/8012
- [ ] https://github.com/excalidraw/excalidraw/pull/6382
- [ ] https://github.com/excalidraw/excalidraw/issues/4847
- [ ] https://github.com/excalidraw/excalidraw/issues/7998
- [ ] https://github.com/excalidraw/excalidraw/issues/7237
- [ ] https://github.com/excalidraw/excalidraw/pull/7722
- [ ] https://github.com/excalidraw/excalidraw/issues/5370
- [ ] https://github.com/excalidraw/excalidraw/issues/3510
- [ ] https://github.com/excalidraw/excalidraw/issues/6619
- [ ] https://github.com/excalidraw/excalidraw/issues/6095
- [ ] https://github.com/excalidraw/excalidraw/issues/7721
- [ ] https://github.com/excalidraw/excalidraw/issues/8088
- [ ] https://github.com/excalidraw/excalidraw/pull/8102
- [ ] https://github.com/excalidraw/excalidraw/issues/8071
- [ ] https://github.com/excalidraw/excalidraw/issues/8101
- [ ] https://github.com/excalidraw/excalidraw/issues/8100
- [ ] https://github.com/excalidraw/excalidraw/pull/8099
- [ ] https://github.com/excalidraw/excalidraw/issues/8094
- [ ] https://github.com/excalidraw/excalidraw/issues/8098
- [ ] https://github.com/excalidraw/excalidraw/issues/8096
- [ ] https://github.com/excalidraw/excalidraw/issues/8095
- [ ] https://github.com/excalidraw/excalidraw/issues/8063
- [ ] https://github.com/excalidraw/excalidraw/issues/8097
- [ ] https://github.com/excalidraw/excalidraw/issues/7900
```

**Comment by Ninja-mann07** [comment]
- 8107 #8110 #8108  #8109 @Ninja-mann07 
![EudckP1XAAMdsps](https://github.com/excalidraw/excalidraw/assets/131006409/8fcf5c7d-8843-47d7-af95-44aa49528b15)
