### ISSUE TITLE
Release v18 🚀

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#8771]
### Docs
- [x] https://github.com/excalidraw/excalidraw/pull/7911
- [x] https://github.com/excalidraw/excalidraw/issues/9149
- [x] Generate changelog
- [x] Revisit examples to use v18 with ESM
- [x] Revisit types as it's no longer needed going into `dist/`
- [x] Upgrade docs-next to v18
- [x] Reuse package example in codesandbox (new setup)
    - [x] `with-browse-script` the be our main example (so that it is runnable in a standalone sandbox)
- [x] https://github.com/excalidraw/excalidraw/issues/7786

### Tasks
- [x] https://github.com/excalidraw/excalidraw/issues/9148
- [x] https://github.com/excalidraw/excalidraw/issues/9137
- [x] https://github.com/excalidraw/excalidraw/issues/9156
- [x] https://github.com/excalidraw/excalidraw/issues/8503
    - [x] use exports fields for types and styles
    - [x] deprecate tsc "node" -> "nodenext" | "bundler"
- [x] https://github.com/excalidraw/excalidraw/issues/8923
    - [x] rebase with changes (nextjs example was moved)
    - [x] update docs & examples with react 19
- [x] Make TS, Vite and esbuild work with build artifacts
   - [x] rebase with changes, correct relative imports, double check math build
- [x] Finalize `storeAction` naming to something more meaningful and possibly switch default

**Comment by bhagat9198** [comment]
Bug Report: Cannot read properties of undefined (ReactCurrentDispatcher) & Incorrect UI Rendering in Vite
Issue Summary
I encountered issues when integrating @excalidraw/excalidraw into my existing React v19 project and a fresh Vite-based React v19 project.

In my existing React (CRA) project, installing and importing @excalidraw/excalidraw resulted in the following runtime error:

`Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at eval (webpack-internal:///../../../node_modules/react/cjs/react-jsx-runtime.development.js:328:51)
    at eval (webpack-internal:///../../../node_modules/react/cjs/react-jsx-runtime.development.js:1313:5)
    at ../../../node_modules/react/cjs/react-jsx-runtime.development.js (http://localhost:3000/static/js/bundle.js:12156:9)
    at __nested_webpack_require_7949150__ (http://localhost:3000/static/js/bundle.js:16143:36)
    at eval (webpack-internal:///../../../node_modules/react/jsx-runtime.js:4:20)
    at ../../../node_modules/react/jsx-runtime.js (http://localhost:3000/static/js/bundle.js:12168:9)
    at __nested_webpack_require_7949150__ (http://localhost:3000/static/js/bundle.js:16143:36)
    at eval (webpack-internal:///./index.tsx:44:75)
    at ./index.tsx (http://localhost:3000/static/js/bundle.js:15630:9)
    at __nested_webpack_require_7949150__ (http://localhost:3000/static/js/bundle.js:16143:36)`

im also sharing my package.json file more clearity on my packages
`{
  "name": "antmedia-cra",
  "version": "3.0.0-SNAPSHOT",
  "private": true,
  "homepage": ".",
  "dependencies": {
    "@antmedia/webrtc_adaptor": "^3.0.0-SNAPSHOT-2024-Dec-24-05-58",
    "@charkour/react-reactions": "^0.11.0",
    "@emotion/react": "^11.14.0",
    "@emotion/styled": "^11.14.0",
    "@excalidraw/excalidraw": "0.15.0",
    "@mui/icons-material": "^6.2.0",
    "@mui/material": "^6.2.0",
    "emoji-picker-react": "^4.12.0",
    "eslint-plugin-react-compiler": "^19.0.0-beta-55955c9-20241229",
    "i18next": "^23.16.2",
    "i18next-browser-languagedetector": "^8.0.2",
    "jest-fixed-jsdom": "^0.0.9",
    "jest-websocket-mock": "^2.5.0",
    "lodash": "^4.17.21",
    "nanoid": "^5.0.9",
    "notistack": "^3.0.1",
    "react": "^19.0.0",
    "react-device-detect": "^2.2.3",
    "react-dom": "^19.0.0",
    "react-i18next": "^15.1.4",
    "react-router-dom": "^7.0.2",
    "react-scripts": "^5.0.1",
    "roughjs": "^4.6.6",
    "slick-carousel": "^1.8.1",
    "url": "^0.11.4",
    "use-sound": "^4.0.3",
    "web-vitals": "^4.2.4",
    "workbox-background-sync": "^7.3.0",
    "workbox-broadcast-update": "^7.3.0",
    "workbox-cacheable-response": "^7.3.0",
    "workbox-core": "^7.3.0",
    "workbox-expiration": "^7.3.0",
    "workbox-google-analytics": "^7.3.0",
    "workbox-navigation-preload": "^7.3.0",
    "workbox-precaching": "^7.3.0",
    "workbox-range-requests": "^7.3.0",
    "workbox-routing": "^7.3.0",
    "workbox-strategies": "^7.3.0",
    "workbox-streams": "^7.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build && node custom-post-build.js",
    "eject": "react-scripts eject",
    "test": "jest --verbose",
    "upload-coverage": "codecov"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@testing-library/dom": "^10.4.0",
    "@testing-library/jest-dom": "^6.6.3",
    "@testing-library/react": "^16.1.0",
    "babel-plugin-istanbul": "^7.0.0",
    "babel-plugin-react-compiler": "^19.0.0-beta-55955c9-20241229",
    "codecov": "^3.8.2",
    "eslint-plugin-react-compiler": "^19.0.0-beta-55955c9-20241229",
    "istanbul": "^0.4.5",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "jest-preview": "^0.3.1"
  }
}
`

App.js file
`import "./App.css";
import { Excalidraw } from "@excalidraw/excalidraw";

function App() {

  return (
      <div style={{ height: "500px" }}>
        /<Excalidraw />
      </div>
  );
}

export default App;`


+++++++++++++++++++++++++++++++++++++++++++++

In a fresh Vite-based React project, Excalidraw did not render as expected. The UI differed from the official documentation, and I could not get the standard Excalidraw editor without customization.

package.json file 
`{
  "name": "exlidraw",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@excalidraw/excalidraw": "^0.18.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.21.0",
    "@types/react": "^19.0.10",
    "@types/react-dom": "^19.0.4",
    "@vitejs/plugin-react": "^4.3.4",
    "eslint": "^9.21.0",
    "eslint-plugin-react-hooks": "^5.1.0",
    "eslint-plugin-react-refresh": "^0.4.19",
    "globals": "^15.15.0",
    "typescript": "~5.7.2",
    "typescript-eslint": "^8.24.1",
    "vite": "^6.2.0"
  }
}
`

App.tsx file 
`import { Excalidraw } from "@excalidraw/excalidraw";
// import "@excalidraw/excalidraw/dist/prod/index.css";

function App() {
  return (
    <>
      <div style={{ height: "500px", width: "500px" }}>
        /<Excalidraw />
      </div>
    </>
  )
}

export default App`

<img width="808" alt="Image" src="https://github.com/user-attachments/assets/069bc948-31c2-420b-b1c2-3e9198221f82" />
<img width="808" alt="Image" src="https://github.com/user-attachments/assets/7244632e-6681-411a-814d-560144dfef05" />
